//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GBASM.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GBASMParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IGBASMListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval([NotNull] GBASMParser.EvalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval([NotNull] GBASMParser.EvalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] GBASMParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] GBASMParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp([NotNull] GBASMParser.OpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp([NotNull] GBASMParser.OpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.jumpflag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpflag([NotNull] GBASMParser.JumpflagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.jumpflag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpflag([NotNull] GBASMParser.JumpflagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.complexop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexop([NotNull] GBASMParser.ComplexopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.complexop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexop([NotNull] GBASMParser.ComplexopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd([NotNull] GBASMParser.CmdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd([NotNull] GBASMParser.CmdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.regop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegop([NotNull] GBASMParser.RegopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.regop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegop([NotNull] GBASMParser.RegopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.flagop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlagop([NotNull] GBASMParser.FlagopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.flagop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlagop([NotNull] GBASMParser.FlagopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex([NotNull] GBASMParser.ComplexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex([NotNull] GBASMParser.ComplexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.loc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoc([NotNull] GBASMParser.LocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.loc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoc([NotNull] GBASMParser.LocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemory([NotNull] GBASMParser.MemoryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemory([NotNull] GBASMParser.MemoryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffset([NotNull] GBASMParser.OffsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffset([NotNull] GBASMParser.OffsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegister([NotNull] GBASMParser.RegisterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegister([NotNull] GBASMParser.RegisterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.wideregister"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWideregister([NotNull] GBASMParser.WideregisterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.wideregister"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWideregister([NotNull] GBASMParser.WideregisterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlag([NotNull] GBASMParser.FlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlag([NotNull] GBASMParser.FlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] GBASMParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] GBASMParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.negvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegvalue([NotNull] GBASMParser.NegvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.negvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegvalue([NotNull] GBASMParser.NegvalueContext context);
}
