//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GBASM.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GBASMParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IGBASMListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval([NotNull] GBASMParser.EvalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval([NotNull] GBASMParser.EvalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] GBASMParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] GBASMParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.sys"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSys([NotNull] GBASMParser.SysContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.sys"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSys([NotNull] GBASMParser.SysContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp([NotNull] GBASMParser.OpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp([NotNull] GBASMParser.OpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.monad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonad([NotNull] GBASMParser.MonadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.monad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonad([NotNull] GBASMParser.MonadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.biad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBiad([NotNull] GBASMParser.BiadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.biad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBiad([NotNull] GBASMParser.BiadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.triad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriad([NotNull] GBASMParser.TriadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.triad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriad([NotNull] GBASMParser.TriadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] GBASMParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] GBASMParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemory([NotNull] GBASMParser.MemoryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.memory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemory([NotNull] GBASMParser.MemoryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffset([NotNull] GBASMParser.OffsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffset([NotNull] GBASMParser.OffsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegister([NotNull] GBASMParser.RegisterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.register"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegister([NotNull] GBASMParser.RegisterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlag([NotNull] GBASMParser.FlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.flag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlag([NotNull] GBASMParser.FlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.db"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDb([NotNull] GBASMParser.DbContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.db"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDb([NotNull] GBASMParser.DbContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] GBASMParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] GBASMParser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSection([NotNull] GBASMParser.SectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSection([NotNull] GBASMParser.SectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] GBASMParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] GBASMParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump([NotNull] GBASMParser.JumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump([NotNull] GBASMParser.JumpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] GBASMParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] GBASMParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] GBASMParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] GBASMParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GBASMParser.negvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegvalue([NotNull] GBASMParser.NegvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GBASMParser.negvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegvalue([NotNull] GBASMParser.NegvalueContext context);
}
